version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./output:/app/output
    networks:
      - default
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
